[package]
name = "walrust"
authors = ["lokiedev"]
description = "Terminal-based wallpaper changer for Hyprpaper written in Rust"
version = "1.0.2"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
image = "0.25.9"
lru = "0.16.2"
ratatui = "0.30.0"
ratatui-image = "10.0.2"
serde_json = "1.0.146"
