[package]
name = "walrust"
authors = ["lokiedev"]
description = "Terminal-based wallpaper changer for Hyprpaper written in Rust"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
image = "0.25.9"
ratatui = "0.29.0"
ratatui-image = "9.0.0"
serde_json = "1.0.146"
